// =============================================================================
// Agent Court — Escrow Client (Solana On-Chain Execution)
// =============================================================================
//
// Interacts with the existing Anchor agent-court escrow program.
// The on-chain program has these relevant instructions:
//   - render_verdict(verdict, split_bps_a, split_bps_b)  — judge signs
//   - claim()                                              — permissionless after verdict
//
// This client calls render_verdict, then claim, to execute the AI tribunal's
// decision on-chain. Uses @coral-xyz/anchor for IDL-based instruction building.
// =============================================================================

import * as anchor from "@coral-xyz/anchor";
import { Program } from "@coral-xyz/anchor";
import { getAssociatedTokenAddressSync } from "@solana/spl-token";
import type { FinalVerdict, VerdictOutcome } from "./types.js";

// --- Anchor IDL Type (minimal, matching lib.rs) ---
// In production, this is generated by `anchor build` into target/types/agent_court.ts.
// For the orchestrator, we only need the verdict-related methods.

type VerdictArg =
  | { refund: Record<string, never> }
  | { release: Record<string, never> }
  | { split: Record<string, never> };

export interface EscrowConfig {
  /** Anchor provider (handles RPC, wallet, signing) */
  provider: anchor.AnchorProvider;
  /** The program instance — load from IDL or workspace */
  program: Program;
  /** Judge authority keypair — signs render_verdict */
  judgeKeypair: anchor.web3.Keypair;
}

export class EscrowClient {
  private provider: anchor.AnchorProvider;
  private program: Program;
  private judge: anchor.web3.Keypair;

  constructor(config: EscrowConfig) {
    this.provider = config.provider;
    this.program = config.program;
    this.judge = config.judgeKeypair;
  }

  /**
   * Execute a final verdict on-chain:
   * 1. Call render_verdict to record the verdict on the escrow PDA
   * 2. Call claim to distribute funds per the verdict
   *
   * Returns the claim transaction signature.
   */
  async executeVerdict(
    verdict: FinalVerdict,
    dispute: {
      escrow_pda: anchor.web3.PublicKey;
      vault_pda: anchor.web3.PublicKey;
      mint: anchor.web3.PublicKey;
      agent_a: anchor.web3.PublicKey;
      agent_b: anchor.web3.PublicKey;
    },
  ): Promise<{ render_tx: string; claim_tx: string }> {
    // --- Step 1: Render Verdict ---
    const { verdictArg, splitBpsA, splitBpsB } = this.encodeVerdict(verdict);

    const renderTx = await this.program.methods
      .renderVerdict(verdictArg, splitBpsA, splitBpsB)
      .accounts({
        judge: this.judge.publicKey,
        escrow: dispute.escrow_pda,
      })
      .signers([this.judge])
      .rpc();

    // --- Step 2: Claim (distribute funds) ---
    const agentATokenAccount = getAssociatedTokenAddressSync(
      dispute.mint,
      dispute.agent_a,
    );
    const agentBTokenAccount = getAssociatedTokenAddressSync(
      dispute.mint,
      dispute.agent_b,
    );

    const claimTx = await this.program.methods
      .claim()
      .accounts({
        claimer: this.judge.publicKey, // Anyone can crank this
        escrow: dispute.escrow_pda,
        vault: dispute.vault_pda,
        mint: dispute.mint,
        agentATokenAccount,
        agentBTokenAccount,
        agentA: dispute.agent_a,
      })
      .signers([this.judge])
      .rpc();

    return { render_tx: renderTx, claim_tx: claimTx };
  }

  /**
   * Convert the AI tribunal's verdict into Anchor-compatible arguments.
   *
   * The on-chain program uses:
   *   verdict: enum { Release, Refund, Split }
   *   split_bps_a: u16  (basis points to Agent A, 0-10000)
   *   split_bps_b: u16  (basis points to Agent B, 0-10000; must sum to 10000 for Split)
   */
  private encodeVerdict(verdict: FinalVerdict): {
    verdictArg: VerdictArg;
    splitBpsA: number;
    splitBpsB: number;
  } {
    switch (verdict.outcome) {
      case "REFUND":
        return {
          verdictArg: { refund: {} },
          splitBpsA: 0,
          splitBpsB: 0,
        };

      case "RELEASE":
        return {
          verdictArg: { release: {} },
          splitBpsA: 0,
          splitBpsB: 0,
        };

      case "SPLIT": {
        const [pRatio, dRatio] = verdict.split_ratio ?? [0.5, 0.5];
        // Convert float ratio to basis points (0-10000)
        const bpsA = Math.round(pRatio * 10_000);
        const bpsB = 10_000 - bpsA; // Ensure exact sum to 10000

        return {
          verdictArg: { split: {} },
          splitBpsA: bpsA,
          splitBpsB: bpsB,
        };
      }

      default:
        throw new Error(`Unknown verdict outcome: ${verdict.outcome}`);
    }
  }

  /**
   * Derive the escrow PDA from the agent pubkeys and service hash.
   * Utility for the orchestrator to find the right escrow account.
   */
  static deriveEscrowPda(
    programId: anchor.web3.PublicKey,
    agentA: anchor.web3.PublicKey,
    agentB: anchor.web3.PublicKey,
    serviceHash: Buffer,
  ): [anchor.web3.PublicKey, number] {
    return anchor.web3.PublicKey.findProgramAddressSync(
      [
        Buffer.from("escrow"),
        agentA.toBuffer(),
        agentB.toBuffer(),
        serviceHash,
      ],
      programId,
    );
  }

  /**
   * Derive the vault PDA from the escrow PDA.
   */
  static deriveVaultPda(
    programId: anchor.web3.PublicKey,
    escrowPda: anchor.web3.PublicKey,
  ): [anchor.web3.PublicKey, number] {
    return anchor.web3.PublicKey.findProgramAddressSync(
      [Buffer.from("vault"), escrowPda.toBuffer()],
      programId,
    );
  }
}
